coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        informational: false
    patch:
      default:
        target: auto
        threshold: 100%
        base: auto
