[package]
name = "lightning-rapid-gossip-sync"
version = "0.0.109"
authors = ["Arik Sosman <git@arik.io>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lightningdevkit/rust-lightning"
edition = "2018"
description = """
Utility to process gossip routing data from Rapid Gossip Sync Server.
"""

[features]
_bench_unstable = []

[dependencies]
lightning = { version = "0.0.109", path = "../lightning" }
bitcoin = { version = "0.28.1", default-features = false }

[dev-dependencies]
lightning = { version = "0.0.109", path = "../lightning", features = ["_test_utils"] }
